config/routes.rb
Rails.application.routes.draw do
  scope RailsCom.default_routes_scope do
    namespace :in, defaults: { namespace: 'in' } do
      root 'home#index'
      controller :home do
        get :index
        get :organs
      end
    end

    namespace :our, defaults: { namespace: 'our' } do
      root 'home#index'
    end

    namespace :board, defaults: { namespace: 'board' } do
      root 'home#index' unless has_named_route? 'board_root'
      controller :home do
        get :index
      end
    end

    namespace :mem, defaults: { namespace: 'mem' } do
      root 'home#index'
    end

    namespace 'org', defaults: { business: 'org' } do
      resources :members, only: [:index, :show] do
        collection do
          get :search
        end
      end
      resources :organs, only: [:index, :show] do
        collection do
          get :form_search
        end
      end

      namespace :me, defaults: { namespace: 'me' } do
        root 'home#index'
        resource :member, except: [:new, :create] do
          member do
            get :qrcodes
            get :qrcode
          end
        end
        resource :organs, except: [:new, :create]
        resource :resign
        resources :departments
        resources :tutorials do
          collection do
            get :tutorings
          end
          member do
            get :perform
          end
        end
        resources :job_transfers do
          get :departments, on: :collection
        end
      end

      namespace :board, defaults: { namespace: 'board' } do
        resources :organs do
          member do
            match :redirect, via: [:get, :post]
          end
        end
        resources :members, only: [:index, :new, :create] do
          collection do
            get :near
            match :logout, via: [:get, :post]
          end
          member do
            match :user_login, via: [:get, :post]
            match :login, via: [:get, :post]
          end
        end
      end

      namespace :panel, defaults: { namespace: 'panel' } do
        root 'home#index'
        resources :organs do
          collection do
            post :search
          end
          member do
            get :children
            post :edit_roles
          end
          resources :organ_domains
          resources :members do
            member do
              post :mock
              post :edit_roles
            end
          end
        end
      end

      namespace :admin, defaults: { namespace: 'admin' } do
        root 'home#index'
        controller :home do
          get :index
        end
        resource :current_organ, controller: 'current_organ'
        resources :organs do
          collection do
            get :all
          end
          member do
            post :edit_roles
          end
          resources :organ_domains
        end
        resources :departments do
          collection do
            get :supports
            get :parents
            get :my
            get :search
            get :filter
          end
          member do
            get :need
          end
          resources :job_titles do
            collection do
              post 'department' => :create_department
            end
            member do
              patch :move_lower
              patch :move_higher
              patch :reorder
            end
          end
          resources :job_descriptions
        end
        resources :super_job_titles do
          member do
            patch :move_lower
            patch :move_higher
            patch :reorder
          end
        end
        resources :members do
          collection do
            get :options
            get :departments
            get :leaders
            patch :sync_all
            get 'add_item/:item' => :add_item, as: :add_item
            get 'remove_item/:item' => :remove_item, as: :remove_item
          end
          member do
            post :edit_roles
            get :token
            patch :mock
          end
          resources :member_departments do
            collection do
              get :options
            end
            member do
              get 'options' => :member_options
            end
          end
          resources :authorized_tokens
        end
        resources :supports do
          collection do
            get :departments
          end
        end
        resources :tutorials do
          collection do
            get :my
          end
        end
        resources :job_transfers do
          member do
            patch :trigger
          end
          collection do
            get :my
          end
        end
        resources :resigns do
          collection do
            get :my
            get :charts
          end
        end
        resources :resign_reasons do
          collection do
            get :parents
          end
        end
        resources :shortcuts
        scope ':record_class/:record_column' do
          resources :department_grants
        end
      end

      namespace :group, defaults: { namespace: 'group' } do
        resources :members
      end

      namespace :my, defaults: { namespace: 'my' } do
        resource :authorized_token
      end

    end
  end
end

app/models/organ.rb
# frozen_string_literal: true

Organ = Org::Organ unless defined? Organ

app/controllers/org/admin/organs_controller.rb
module Org
  class Admin::OrgansController < Panel::OrgansController
    before_action :set_organ, only: [:show, :edit, :update, :destroy]

    def index
      q_params = {}
      q_params.merge! parent_id: current_organ.id

      @organs = Organ.default_where(q_params).order(id: :desc).page(params[:page])
    end

    def new
      @organ = Organ.new
      @organ.area || @organ.build_area
    end

    def create
      if organ_params.select(&->(k, v){ k.start_with?('parent_ancestors') && v.present? }).values.blank?
        @organ = Organ.new organ_params.merge!(parent_id: current_organ.id)
      else
        @organ = Organ.new(organ_params)
      end

      unless @organ.save
        render :new, locals: { model: @organ }, status: :unprocessable_entity
      end
    end

    def edit
      @organ.area || @organ.build_area
    end

    private
    def set_organ
      @organ = Organ.find params[:id]
    end

    def organ_params
      params.fetch(:organ, {}).permit(
        :name,
        :code,
        :logo,
        :bar_logo,
        :bar_logo_invert,
        :name_short,
        :address,
        :service_url,
        :parent_ancestors,
        :area_ancestors
      )
    end

    def organ_limit_params
      params.fetch(:organ, {}).permit(
        :limit_office,
        :limit_wechat
      )
    end

  end
end

app/controllers/org/board/organs_controller.rb
module Org
  class Board::OrgansController < Board::BaseController
    before_action :set_organ, only: [:show, :edit, :update, :redirect, :destroy]
    before_action :set_new_organ, only: [:index, :new]
    before_action :set_create_organ, only: [:create]
    before_action :set_role, only: [:new]
    before_action :set_roles, only:[:index, :create]

    def index
      q_params = {}
      #q_params.merge! provider_id: [current_organ.id, nil] if current_organ
      q_params.merge! 'who_roles.role_id' => params[:role_id] if params[:role_id].present?

      @created_organs = current_user.created_organs.includes(:organ_domains).default_where(q_params).order(id: :desc)
      @accounts = current_user.accounts.each_with_object({}) { |k, h| h[k] = k.organs.where.not(id: current_user.created_organ_ids).default_where(q_params) }
      @accounts.merge! current_user.oauth_users.each_with_object({}) { |k, h| h[k] = k.organs.where.not(id: current_user.created_organ_ids).default_where(q_params) }
    end

    def create
      if @organ.save
        render :create, locals: { model: @organ }
      else
        render :new, locals: { model: @organ }, status: :unprocessable_entity
      end
    end

    def redirect
      member = current_user.members.find_by(organ_id: @organ.id)

      if RailsOrg.config.independent
        redirect_to({ controller: '/me/home', host: @organ.admin_host, auth_token: member.auth_token }, allow_other_host: true)
      else
        current_authorized_token.update member_id: member.id
        redirect_to controller: '/admin/home'
      end
    end

    private
    def set_organ
      @organ = current_user.organs.find(params[:id])
    end

    def set_new_organ
      @organ = current_user.created_organs.build(organ_params)
      @organ.role_whos.build(role_id: params[:role_id]) if params[:role_id].present?
    end

    def set_create_organ
      @organ = current_user.created_organs.build(organ_params)
      @member = @organ.members.build(
        identity: current_authorized_token.identity,
        own: true,
        **organ_params.slice(:role_whos_attributes)
      )
      @member.wechat_openid = current_authorized_token.uid if @member.respond_to? :wechat_openid
    end

    def set_role
      if params[:role_id].present?
        @role = Roled::Role.find params[:role_id]
      end
    end

    def set_roles
      if params[:role_id].present?
        @roles = Roled::Role.visible.where(id: params[:role_id])
      else
        @roles = Roled::Role.visible.where.not(tip: nil)
      end
    end

    def organ_params
      _p = params.fetch(:organ, {}).permit(
        :name,
        :logo,
        role_whos_attributes: {}
      )
      _p.merge! provider_id: current_organ.id if current_organ
      _p
    end

  end
end

app/controllers/org/controller/panel.rb
module Org
  module Controller::Panel
    extend ActiveSupport::Concern

    def current_organ
      return @current_organ if defined?(@current_organ)
      return if params[:namespace] == 'panel' && Rails.application.routes.default_url_options[:host] == request.host

      if current_organ_domain
        @current_organ = current_organ_domain.organ
      elsif current_member
        @current_organ = current_member.organ
      end
      logger.debug "\e[35m  Login as organ: #{@current_organ&.name}, ID: #{@current_organ&.id}  \e[0m"
      @current_organ
    end

  end
end

app/controllers/org/layout/panel.rb
module Org
  module Layout::Panel
    extend ActiveSupport::Concern

    included do
      layout 'panel'
    end

    class_methods do
      def local_prefixes
        [controller_path, 'org/panel/base', 'panel']
      end
    end

  end
end

app/controllers/org/me/organs_controller.rb
module Org
  class Me::OrgansController < Me::BaseController
    include Org::Layout::Me
    before_action :set_organ, only: [:show, :edit, :update, :destroy]

    def index
      @organs = current_organ.children
      if @organs.blank?
        redirect_to controller: '/me/home'
      end
    end

    def destroy
      if current_user.id == @organ.creator_id
        @organ.destroy
      end
    end

    private
    def set_organ
      @organ = current_member.organ
    end

  end
end

app/controllers/org/mine/organs_controller.rb
class Org::Mine::OrgansController < Org::Mine::BaseController
  before_action :set_organ, only: [:show, :login, :edit, :update, :destroy]

  def index
    @members = current_user.members.page(params[:page])
    session.delete :organ_token
  end

  def new
    @member = current_user.members.build
    @organ = @member.build_organ
  end

  def create
    parent_uuid = params.dig(:member, :parent_uuid)
    if parent_uuid.present?
      parent = Organ.find_by organ_uuid: parent_uuid
      organ_params.merge! parent_id: parent.id
    end
    @member = current_user.members.build(member_params)
    @member.build_organ(organ_params)

    unless @member.save
      render :new, locals: { model: @member }, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    @organ.assign_attributes(organ_params)

    unless @organ.save
      render :edit, locals: { model: @organ }, status: :unprocessable_entity
    end
  end

  def destroy
    @organ.destroy
  end

  private
  def set_member
    @member = current_user.members.find params[:member_id]
  end

  def set_organ
    @organ = Organ.find(params[:id])
  end

  def member_params
    p = params.fetch(:member, {}).permit(:identity)
    p.merge! owned: true
  end

  def organ_params
    params.fetch(:member, {}).fetch(:organ_attributes, {}).permit(
      :name,
      :logo
    )
  end

end

app/controllers/org/my/organs_controller.rb
class Org::My::OrgansController < Org::My::BaseController
  before_action :set_organ, only: [:show, :login, :edit, :update, :destroy]

  def index
    @members = current_user.members.page(params[:page])
    session.delete :organ_token
  end

  def new
    @member = current_user.members.build
    @organ = @member.build_organ
  end

  def create
    parent_uuid = params.dig(:member, :parent_uuid)
    if parent_uuid.present?
      parent = Organ.find_by organ_uuid: parent_uuid
      organ_params.merge! parent_id: parent.id
    end
    @member = current_user.members.build(member_params)
    @member.build_organ(organ_params)

    unless @member.save
      render :new, locals: { model: @member }, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    @organ.assign_attributes(organ_params)

    unless @organ.save
      render :edit, locals: { model: @organ }, status: :unprocessable_entity
    end
  end

  def destroy
    @organ.destroy
  end

  private
  def set_member
    @member = current_user.members.find params[:member_id]
  end

  def set_organ
    @organ = Organ.find(params[:id])
  end

  def member_params
    p = params.fetch(:member, {}).permit(
      :identity
    )
    p.merge! owned: true
    unless p[:identity]
      p.merge! identity: current_account.identity
    end
    p
  end

  def organ_params
    params.fetch(:member, {}).fetch(:organ_attributes, {}).permit(
      :name,
      :logo
    )
  end

end

app/controllers/org/organs_controller.rb
module Org
  class OrgansController < BaseController
    before_action :set_organ, only: [:show]

    def index
      q_params = {
        parent_id: current_organ.id,
        allow: { parent_id: nil }
      }

      @organs = Organ.with_attached_logo.default_where(q_params).order(id: :desc).page(params[:page])
    end

    def show
    end

    def form_search
      q_params = {}
      q_params.merge! params.permit('name-like')

      @organs = Organ.default_where(q_params)
    end

    private
    def set_organ
      @organ = Organ.find params[:id]
    end

  end
end

app/controllers/org/our/organs_controller.rb
class Org::Our::OrgansController < Org::Our::BaseController
  before_action :set_organ, only: [:edit, :update, :destroy]

  def show
  end

  def edit
  end

  def update
    @organ.assign_attributes(organ_params)

    if @organ.save
      render 'update'
    else
      render :edit
    end
  end

  def destroy
    @organ.destroy
  end

  private
  def set_organ
    @organ = current_organ
  end

  def organ_params
    params.fetch(:organ, {}).permit(
      :name,
      :logo,
      :name_short,
      :parent_ancestors,
      :area_ancestors
    )
  end

  def organ_limit_params
    params.fetch(:organ, {}).permit(
      :limit_office,
      :limit_wechat
    )
  end

end

app/controllers/org/panel/base_controller.rb
module Org
  class Panel::BaseController < PanelController
  end
end

app/controllers/org/panel/home_controller.rb
module Org
  class Panel::HomeController < Panel::BaseController

    def index
    end

  end
end

app/controllers/org/panel/members_controller.rb
module Org
  class Panel::MembersController < Panel::BaseController
    before_action :set_organ
    before_action :set_member, only: [:show, :edit, :update, :destroy, :actions, :mock, :edit_roles]
    before_action :set_new_member, only: [:new, :create]

    def index
      q_params = {}
      q_params.merge! params.permit(:id, :identity, 'name-like', :enabled)

      @members = @organ.members.includes(:account, :roles).default_where(q_params).order(id: :desc).page(params[:page])
    end

    def mock
      redirect_to({ controller: '/admin/home', host: @organ.admin_host, auth_token: @member.auth_token }, allow_other_host: true)
    end

    def edit_roles
      @roles = @member.visible_roles
    end

    private
    def set_organ
      @organ = Organ.find params[:organ_id]
    end

    def set_member
      @member = @organ.members.find(params[:id])
    end

    def set_new_member
      @member = @organ.members.build member_params
    end

    def member_params
      params.fetch(:member, {}).permit(
        :name,
        :identity,
        :join_on,
        :enabled,
        :wechat_openid,
        :corp_userid,
        :avatar,
        role_whos_attributes: [:id, :role_id, :_destroy],
        member_departments_attributes: {},
      )
    end

  end
end

app/controllers/org/panel/organ_domains_controller.rb
module Org
  class Panel::OrganDomainsController < Panel::BaseController
    before_action :set_organ
    before_action :set_organ_domain, only: [:show, :edit, :update, :destroy, :actions]
    before_action :set_new_organ_domain, only: [:new, :create]

    def index
      @organ_domains = @organ.organ_domains.page(params[:page])
    end

    private
    def set_organ
      @organ = Organ.find params[:organ_id]
    end

    def set_organ_domain
      @organ_domain = @organ.organ_domains.find(params[:id])
    end

    def set_new_organ_domain
      @organ_domain = @organ.organ_domains.build(organ_domain_params)
    end

    def organ_domain_params
      params.fetch(:organ_domain, {}).permit(
        :domain,
        :subdomain,
        :host,
        :default,
        :appid,
        :scheme,
        :kind,
        :beian,
        :redirect_controller,
        :redirect_action,
      )
    end

  end
end

app/views/org/panel/organs/_edit_form.html.erb
<%= form_with theme: 'modal', model: @organ, url: { action: 'update' } do |f| %>
  <%= render 'modal_header' %>
  <section class="modal-card-body">
    <%= render 'error_messages', target: @organ %>
    <%= render partial: 'com/nodes/children_select', locals: { f: f, node: Org::Organ.root } %>
    <%= render partial: 'form', locals: { f: f } %>
  </section>
  <%= f.submit %>
<% end %>

app/views/org/panel/organs/_filter_form.html.erb
<%= form_with theme: 'search', model: Org::Organ.new do |f| %>
  <div class="field-body">
    <%= f.number_field :id %>
    <%= f.text_field 'name-like' %>
    <div class="field is-narrow">
      <%= f.submit %>
      <%= link_to t('.clear'), filter_params(except: [:id, 'name-like']), class: 'button is-light' %>
    </div>
  </div>
<% end %>

app/views/org/panel/organs/_form.html.erb
<%= f.text_field :name, required: true %>
<%= f.text_field :name_short %>
<%= f.file_field :logo %>
<%= f.text_field :license %>
<%= render partial: 'com/nodes/outer_select', locals: { f: f, outer: 'area', node: @organ.area } if defined? RailsProfile %>
<%= f.text_area :address %>

app/views/org/panel/organs/_index_thead.html.erb
<th>
  <%= Org::Organ.human_attribute_name(:name) %>(<%= Org::Organ.human_attribute_name(:name_short) %>)
</th>
<th><%= Org::Organ.human_attribute_name(:logo) %></th>
<th><%= Org::Organ.human_attribute_name(:domain) %></th>
<th>
  <p><%= Org::Organ.human_attribute_name(:area_id) %></p>
  <p><%= Org::Organ.human_attribute_name(:address) %></p>
</th>
<th><%= Org::Organ.human_attribute_name(:official) %></th>
<th><%= Org::Organ.human_attribute_name(:roles) %></th>
<th></th>

app/views/org/panel/organs/_new_form.html.erb
<%= form_with theme: 'modal', model: @organ, url: { action: 'create' } do |f| %>
  <%= render 'modal_header' %>
  <section class="modal-card-body">
    <%= render 'error_messages', target: @organ %>
    <%= render partial: 'com/nodes/children_select', locals: { f: f, node: Org::Organ.new } %>
    <%= render partial: 'form', locals: { f: f } %>
  </section>
  <%= f.submit %>
<% end %>

app/views/org/panel/organs/_organ.html.erb
<tr>
  <td>
    <%= organ.name %>
    <% if organ.name_short.present? %>
      (<%= organ.name_short %>)
    <% end %>
  </td>
  <td><%= image_tag organ.logo.variant(resize_to_limit: [30, 30]) if organ.logo.attached? %></td>
  <td><%= organ.domain %></td>
  <td>
    <p><%= organ.area&.full_name %></p>
    <p><%= organ.address %></p>
  </td>
  <td>
    <div data-controller="input">
      <%= check_box_tag '[organ]official', nil, organ.official, data: { method: :patch, remote: true, confirm: t('.confirm'), url: panel_organ_path(organ), action: 'input#submit' }, id: nil, class: 'switch is-rounded' %>
      <label></label>
    </div>
  </td>
  <td>
    <div>
      <% organ.roles.pluck(:name).each do |role| %>
        <span><%= role %></span>
      <% end %>
      <%= link_to edit_admin_who_roles_path('Organ', organ.id), aria: { label: t('role.admin.who_roles.edit.title') }, remote: true do %>
        <i class="fas fa-user-shield"></i>
      <% end %>
    </div>
  </td>
  <td>
    <%= link_to({ action: 'edit', id: organ.id }, { aria: { label: t('.edit') }, remote: true, class: 'button is-small is-rounded is-light' }) do %>
      <i class="fas fa-pencil-alt"></i>
    <% end %>
    <%= link_to({ action: 'destroy', id: organ.id }, { method: :delete, aria: { label: t('.destroy') }, data: { confirm: t('.confirm') }, class: 'button is-small is-rounded is-light' }) do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
    <%= link_to admin_root_url(host: organ.host), aria: { label: t('.mock') }, class: 'button is-small is-rounded is-light' do %>
      <i class="fas fa-hand-point-right"></i>
    <% end %>
  </td>
</tr>

app/views/org/panel/organs/_organ_options.html.erb
<div data-action="click->typer#choose" data-id="<%= model.id %>" data-name="<%= model.name %>" class="panel-block">
  <span><%= image_tag model.logo, class: 'image is-16x16' if model.logo.attached? %></span>
  <span class="ml-1"><%= model.name %></span>
  <span class="text-grey">(<%= model.id %>)</span>
</div>

app/views/org/panel/organs/_show_table.html.erb
<div>
  <dt><%= Org::Organ.human_attribute_name(:name) %></dt>
  <dd><%= @organ.name %></dd>
</div>
<div>
  <dt><%= Org::Organ.human_attribute_name(:name_short) %></dt>
  <dd><%= @organ.name_short %></dd>
</div>
<div>
  <dt><%= Org::Organ.human_attribute_name(:area_id) %></dt>
  <dd><%= @organ.area&.full_name %></dd>
</div>
<div>
  <dt><%= Org::Organ.human_attribute_name(:license) %></dt>
  <dd><%= @organ.license %></dd>
</div>
<div>
  <dt></dt>
  <dd>
    <%= image_tag @scene.qrcode_data_url, class: 'image' if @scene %>
  </dd>
</div>

app/views/org/panel/organs/children.html.erb
<%= render 'index_bar' %>
<%= render 'index_actions' %>

<%= render layout: 'index_table' do %>
  <%= render partial: 'index_tbody', layout: 'index_tr', collection: @organs, as: :model %>
<% end %>

<%= paginate @organs %>

app/views/org/panel/organs/edit_roles.turbo_stream.erb
<%= turbo_stream.append 'body', partial: 'role_form', layout: 'modal_form', locals: { model: @organ } %>

app/views/org/panel/organs/search.turbo_stream.erb
<%= turbo_stream.update 'organs_content', partial: 'organ_options', collection: @organs, as: :model %>